// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Domain$HeroGuild = require("./Domain.bs.js");

function initHero(param) {
  return /* record */[/* heroes : [] */0];
}

function heroReducer(state, action) {
  return /* record */[/* heroes : :: */[
            action[0],
            state[/* heroes */0]
          ]];
}

var HeroState = /* module */[
  /* initHero */initHero,
  /* heroReducer */heroReducer
];

function initQuest(param) {
  return /* record */[
          /* pendingQuests : [] */0,
          /* completedQuests : [] */0
        ];
}

function questReducer(state, action) {
  if (action.tag) {
    var questContext = action[0];
    return /* record */[
            /* pendingQuests */List.filter((function (item) {
                      return item[/* id */0] !== questContext[/* id */0];
                    }))(state[/* pendingQuests */0]),
            /* completedQuests : :: */[
              Domain$HeroGuild.SimpleQuestRunner[/* run */2](action[1], questContext),
              state[/* completedQuests */1]
            ]
          ];
  } else {
    return /* record */[
            /* pendingQuests : :: */[
              action[0],
              state[/* pendingQuests */0]
            ],
            /* completedQuests */state[/* completedQuests */1]
          ];
  }
}

var QuestState = /* module */[
  /* initQuest */initQuest,
  /* questReducer */questReducer
];

exports.HeroState = HeroState;
exports.QuestState = QuestState;
/* Domain-HeroGuild Not a pure module */
