// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


function relationshipToJs(param) {
  return {
          myId: param[/* myId */0],
          towardsId: param[/* towardsId */1],
          value: param[/* value */2],
          bond: param[/* bond */3]
        };
}

function relationshipFromJs(param) {
  return /* record */[
          /* myId */param.myId,
          /* towardsId */param.towardsId,
          /* value */param.value,
          /* bond */param.bond
        ];
}

exports.relationshipToJs = relationshipToJs;
exports.relationshipFromJs = relationshipFromJs;
/* No side effect */
