// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Styles$HeroGuild = require("../Styles.bs.js");
var HeroForm$HeroGuild = require("./HeroForm.bs.js");

function App(Props) {
  var match = React.useReducer((function (state, action) {
          return /* record */[/* heroes : :: */[
                    action[0],
                    state[/* heroes */0]
                  ]];
        }), /* record */[/* heroes : [] */0]);
  var heroDispatch = match[1];
  var heroState = match[0];
  var submitHero = function (hero) {
    Curry._1(heroDispatch, /* AddHero */[hero]);
    console.log(heroState);
    return /* () */0;
  };
  return React.createElement("div", undefined, React.createElement("p", undefined, "This is a most basic component."), React.createElement("div", {
                  className: Styles$HeroGuild.card
                }, React.createElement(HeroForm$HeroGuild.make, {
                      submitHero: submitHero
                    })));
}

var make = App;

exports.make = make;
/* react Not a pure module */
