// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Styles$HeroGuild = require("../Styles.bs.js");
var AppState$HeroGuild = require("../AppState.bs.js");
var HeroForm$HeroGuild = require("./HeroForm.bs.js");
var GuildInfo$HeroGuild = require("./GuildInfo.bs.js");

function App(Props) {
  var match = React.useReducer(AppState$HeroGuild.HeroState[/* heroReducer */1], AppState$HeroGuild.HeroState[/* initHero */0](/* () */0));
  var heroDispatch = match[1];
  var submitHero = function (hero) {
    return Curry._1(heroDispatch, /* AddHero */[hero]);
  };
  return React.createElement("div", {
              className: Styles$HeroGuild.flexColumn
            }, React.createElement("h2", undefined, "Heroes Guild"), React.createElement("div", undefined, React.createElement(HeroForm$HeroGuild.make, {
                      submitHero: submitHero
                    })), React.createElement(GuildInfo$HeroGuild.make, {
                  heroes: match[0][/* heroes */0]
                }));
}

var make = App;

exports.make = make;
/* react Not a pure module */
