// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var Domain$HeroGuild = require("../domain/Domain.bs.js");

function GuildInfo$HeroCard(Props) {
  var hero = Props.hero;
  var view = Domain$HeroGuild.Hero[/* view */1](hero);
  return React.createElement("div", {
              className: "max-w-xs rounded overflow-hidden shadow-lg p-2 m-2"
            }, React.createElement("p", undefined, "Name: " + view[/* name */1]), React.createElement("p", undefined, "Skill: " + view[/* skill */2].toString()));
}

var HeroCard = /* module */[/* make */GuildInfo$HeroCard];

function GuildInfo(Props) {
  var heroes = Props.heroes;
  var heroCards = $$Array.of_list(List.map((function (hero) {
              return React.createElement(GuildInfo$HeroCard, {
                          hero: hero,
                          key: Domain$HeroGuild.Hero[/* getId */0](hero)
                        });
            }), heroes));
  return React.createElement("div", {
              className: "p-2"
            }, "Your Heroes", React.createElement("div", {
                  className: "flex flex-col sm:flex-row flex-wrap"
                }, heroCards));
}

var make = GuildInfo;

exports.HeroCard = HeroCard;
exports.make = make;
/* react Not a pure module */
