// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var Forms$HeroGuild = require("./Forms.bs.js");
var Domain$HeroGuild = require("../domain/Domain.bs.js");
var Styles$HeroGuild = require("../Styles.bs.js");

function HeroForm(Props) {
  var submitHero = Props.submitHero;
  var match = React.useState((function () {
          return "";
        }));
  var setName = match[1];
  var name = match[0];
  var match$1 = React.useState((function () {
          return 0.5;
        }));
  var setSkill = match$1[1];
  var skill = match$1[0];
  return React.createElement("div", {
              className: "max-w-md p-2"
            }, React.createElement("p", undefined, "Create a hero by entering values below."), React.createElement(Forms$HeroGuild.TextInput[/* make */0], {
                  label: "Hero Name",
                  value: name,
                  onChange: (function ($$event) {
                      var value = $$event.target.value;
                      return Curry._1(setName, (function (param) {
                                    return value;
                                  }));
                    })
                }), React.createElement(Forms$HeroGuild.NumberInput[/* make */0], {
                  label: "Skill (0-1)",
                  value: skill,
                  step: 0.01,
                  onChange: (function ($$event) {
                      var value = $$event.target.value;
                      if (isNaN(Number(value))) {
                        return 0;
                      } else {
                        var f = Caml_format.caml_float_of_string(value);
                        return Curry._1(setSkill, (function (param) {
                                      return f;
                                    }));
                      }
                    })
                }), React.createElement("button", {
                  className: Styles$HeroGuild.btnBlue,
                  type: "submit",
                  onClick: (function (param) {
                      return Curry._1(submitHero, Domain$HeroGuild.Hero[/* make */3](name, skill));
                    })
                }, "submit"));
}

var make = HeroForm;

exports.make = make;
/* react Not a pure module */
