// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function QuestUi$QuestCard(Props) {
  var quest = Props.quest;
  return React.createElement("div", {
              className: "max-w-xs rounded overflow-hidden shadow-lg p-2 m-2"
            }, React.createElement("p", undefined, "Description: " + quest[/* description */0]), React.createElement("p", undefined, "Challenge: " + quest[/* challenge */1].toString()), React.createElement("p", undefined, "Location: " + (
                  quest[/* location */2] ? "Ruin" : "Forest"
                )));
}

var QuestCard = /* module */[/* make */QuestUi$QuestCard];

exports.QuestCard = QuestCard;
/* react Not a pure module */
