// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Uuid$HeroGuild = require("../Uuid.bs.js");
var Styles$HeroGuild = require("../Styles.bs.js");

function QuestUi$QuestCard(Props) {
  var quest = Props.quest;
  return React.createElement("div", {
              className: "max-w-xs rounded overflow-hidden shadow-lg p-2 m-2"
            }, React.createElement("p", undefined, "Description: " + quest[/* description */1]), React.createElement("p", undefined, "Challenge: " + quest[/* challenge */2].toString()), React.createElement("p", undefined, "Location: " + (
                  quest[/* location */3] ? "Ruin" : "Forest"
                )), React.createElement("p", undefined, "Quest Type: " + (
                  quest[/* questType */4] ? "Guard" : "Clear Monsters"
                )));
}

var QuestCard = /* module */[/* make */QuestUi$QuestCard];

function QuestUi$QuestOutcomeCard(Props) {
  Props.questHistory;
  return React.createElement("div", {
              className: "rounded overflow-hidden shadow-lg p-2 m-2"
            }, React.createElement("p", undefined, "encounter => result"));
}

var QuestOutcomeCard = /* module */[/* make */QuestUi$QuestOutcomeCard];

function QuestUi(Props) {
  var pendingQuests = Props.pendingQuests;
  Props.completedQuests;
  var handleAddQuest = Props.handleAddQuest;
  Props.handleResolveQuest;
  var generateQuest = function (param) {
    return /* record */[
            /* id */Uuid$HeroGuild.questId(/* () */0),
            /* description */"Another Dummy Quest",
            /* challenge */0.5,
            /* location : Forest */0,
            /* questType : ClearMonsters */0
          ];
  };
  var questCards = $$Array.of_list(List.map((function (quest) {
              return React.createElement(QuestUi$QuestCard, {
                          quest: quest,
                          key: quest[/* id */0]
                        });
            }), pendingQuests));
  return React.createElement("div", {
              className: "m-2"
            }, React.createElement("button", {
                  className: Styles$HeroGuild.btnBlue,
                  type: "button",
                  onClick: (function (param) {
                      return Curry._1(handleAddQuest, generateQuest(/* () */0));
                    })
                }, "Generate Quest"), React.createElement("div", {
                  className: "flex flex-col sm:flex-row"
                }, questCards));
}

var make = QuestUi;

exports.QuestCard = QuestCard;
exports.QuestOutcomeCard = QuestOutcomeCard;
exports.make = make;
/* react Not a pure module */
