// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function relationshipToJs(param) {
  return {
          myId: param[/* myId */0],
          towardsId: param[/* towardsId */1],
          value: param[/* value */2],
          bond: param[/* bond */3]
        };
}

function relationshipFromJs(param) {
  return /* record */[
          /* myId */param.myId,
          /* towardsId */param.towardsId,
          /* value */param.value,
          /* bond */param.bond
        ];
}

function heroToJs(hero) {
  return {
          id: hero[/* id */0],
          name: hero[/* name */1],
          skill: hero[/* skill */2],
          relationships: List.map(relationshipToJs, hero[/* relationships */3])
        };
}

exports.relationshipToJs = relationshipToJs;
exports.relationshipFromJs = relationshipFromJs;
exports.heroToJs = heroToJs;
/* No side effect */
