// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");

var flexColumn = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexDirection(Css.column),
        /* [] */0
      ]
    ]);

var form = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexDirection(Css.column),
        /* :: */[
          Css.backgroundColor(Css.white),
          /* [] */0
        ]
      ]
    ]);

Css.$$global("input", /* :: */[
      Css.margin(Css.px(10)),
      /* [] */0
    ]);

exports.flexColumn = flexColumn;
exports.form = form;
/* flexColumn Not a pure module */
