// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


var btn = "font-bold py-2 px-4 rounded";

var btnBlue = "font-bold py-2 px-4 rounded bg-blue-500 hover:bg-blue-700 text-white";

var input = "max-w-xs appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500";

var formLabel = "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2";

exports.input = input;
exports.formLabel = formLabel;
exports.btn = btn;
exports.btnBlue = btnBlue;
/* No side effect */
