// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");

var card = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexDirection(Css.column),
        /* :: */[
          Css.alignItems(Css.stretch),
          /* :: */[
            Css.backgroundColor(Css.blue),
            /* [] */0
          ]
        ]
      ]
    ]);

var form = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexDirection(Css.column),
        /* :: */[
          Css.backgroundColor(Css.white),
          /* [] */0
        ]
      ]
    ]);

Css.$$global("input", /* :: */[
      Css.margin(Css.px(10)),
      /* [] */0
    ]);

exports.card = card;
exports.form = form;
/* card Not a pure module */
